import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import ReactFlow, { Background, Controls, MarkerType } from "reactflow";
import "reactflow/dist/style.css";
import {
  getQualitativeSession,
  submitCodeReview,
  groupCodesIntoThemes,
  submitThemeReview,
  defineQualitativeThemes,
  finalizeQualitativeThemes,
} from "../api.js";
import {
  FINALIZE_POLL_INTERVAL_MS,
  FINALIZE_HEADLINE,
  isFinalizing,
  isFinalizeFailed,
  isFinalizeComplete,
  finalizeStepText,
  finalizeErrorMessage,
  buildFinalizedOutcome,
} from "../qualitativeFinalizePolling.js";

/*
 * QualitativeReview
 * -------------------------------------------------------------
 * Walks a researcher through Braun & Clarke's reflexive thematic
 * analysis, stages 1-6, for one open-text column:
 *
 *   1-2. Familiarize + initial coding  -- already generated by /run
 *        over the FULL corpus of this column; this component fetches
 *        and displays them. Coding stays interactive (accept/decline/
 *        edit each suggested code).
 *   3.   Search for themes             -- AI clusters accepted codes,
 *        shown as a draggable node graph the researcher can regroup.
 *   4.   Review themes                 -- AI flags each candidate theme
 *        keep/merge/split against the full dataset; the researcher
 *        accepts or dismisses each suggestion, then accepts/declines/
 *        edits the resulting theme set.
 *   5.   Define & name themes          -- read-only: central organizing
 *        concept + subthemes per theme.
 *   6.   Produce the report            -- "Finalize" writes the
 *        Chapter 4 result.
 * -------------------------------------------------------------
 */

function stepForPhase(phase) {
  if (phase === "defining" || phase === "complete" || phase === "finalizing" || phase === "failed") return "define";
  if (phase === "theming_review") return "group";
  return "familiarize";
}

function TAG_LABEL(status) {
  if (status === "accepted") return "Accepted";
  if (status === "declined") return "Declined";
  return "Pending";
}

const THEME_COLORS = [
  "#dda622",
  "#245b42",
  "#a63d32",
  "#3a6ea5",
  "#7a4fa3",
  "#b0762a",
];

function themeLabel(theme) {
  return theme.edited_name || theme.name;
}

function computeLayout(acceptedCodes, themes, membership) {
  const themeX = new Map();
  themes.forEach((theme, index) => {
    themeX.set(theme.id, index * 260 + 40);
  });

  const nodes = [];
  const edges = [];

  themes.forEach((theme, index) => {
    const x = themeX.get(theme.id);
    const color = THEME_COLORS[index % THEME_COLORS.length];
    nodes.push({
      id: `theme:${theme.id}`,
      type: "default",
      position: { x, y: 0 },
      draggable: false,
      selectable: false,
      style: {
        width: 220,
        background: `${color}1a`,
        border: `2px solid ${color}`,
        borderRadius: 12,
        fontWeight: 700,
        padding: 8,
        fontSize: 13,
      },
      data: {
        label: themeLabel(theme),
      },
    });
  });

  const stackIndex = new Map();
  acceptedCodes.forEach((code) => {
    const themeId = membership[code.id] || themes[0]?.id;
    const x = themeX.get(themeId) ?? 40;
    const slot = stackIndex.get(themeId) || 0;
    stackIndex.set(themeId, slot + 1);
    const themeIndex = themes.findIndex((t) => t.id === themeId);
    const color = THEME_COLORS[Math.max(themeIndex, 0) % THEME_COLORS.length];

    nodes.push({
      id: `code:${code.id}`,
      type: "default",
      position: { x, y: 110 + slot * 64 },
      style: {
        width: 220,
        background: "#fffdf8",
        border: `1px solid ${color}`,
        borderRadius: 8,
        fontSize: 12,
        padding: 6,
      },
      data: {
        label: code.edited_name || code.code_name,
      },
    });

    if (themeId) {
      edges.push({
        id: `edge:${code.id}:${themeId}`,
        source: `code:${code.id}`,
        target: `theme:${themeId}`,
        style: { stroke: color, strokeWidth: 1.5 },
        markerEnd: { type: MarkerType.ArrowClosed, color },
      });
    }
  });

  return { nodes, edges, themeX };
}

function VerdictBanner({ theme, activeThemes, onAcceptMerge, onAcceptSplit, onDismiss, busy }) {
  if (!theme.verdict || theme.verdict === "keep") return null;

  if (theme.verdict === "merge") {
    const target = activeThemes.find((t) => t.id === theme.merge_with);
    return (
      <div className="qualitative-verdict-banner">
        <span>
          AI suggests merging into <strong>{target ? themeLabel(target) : "another theme"}</strong>
          {theme.verdict_notes ? `: ${theme.verdict_notes}` : ""}
        </span>
        {target && (
          <div className="qualitative-verdict-actions">
            <button className="btn btn-secondary" type="button" onClick={() => onAcceptMerge(theme)} disabled={busy}>
              Accept merge
            </button>
            <button className="btn btn-secondary" type="button" onClick={() => onDismiss(theme)} disabled={busy}>
              Keep separate
            </button>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="qualitative-verdict-banner">
      <span>AI suggests this theme covers more than one idea{theme.verdict_notes ? `: ${theme.verdict_notes}` : ""}</span>
      <div className="qualitative-verdict-actions">
        <button className="btn btn-secondary" type="button" onClick={() => onAcceptSplit(theme)} disabled={busy}>
          Split into two
        </button>
        <button className="btn btn-secondary" type="button" onClick={() => onDismiss(theme)} disabled={busy}>
          Keep as one theme
        </button>
      </div>
    </div>
  );
}

export default function QualitativeReview({ conversationId, column, onFinalized }) {
  const [session, setSession] = useState(null);
  const [step, setStep] = useState("familiarize");
  const [codeSelections, setCodeSelections] = useState({});
  const [themeSelections, setThemeSelections] = useState({});
  const [activeThemes, setActiveThemes] = useState([]);
  const [membership, setMembership] = useState({});
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const onFinalizedRef = useRef(onFinalized);
  onFinalizedRef.current = onFinalized;

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError("");

    getQualitativeSession(conversationId, column)
      .then((res) => {
        if (cancelled) return;
        setSession(res.session);
        setStep(stepForPhase(res.session.phase));
      })
      .catch((err) => {
        if (!cancelled) setError(err.message || "Could not load the qualitative review.");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [conversationId, column]);

  /*
   * Finalize (stage 6) runs as a background task on the backend -- the
   * POST that starts it returns almost immediately with phase
   * "finalizing", not the finished result. Poll the session until it
   * reaches "complete" or "failed". This effect is keyed off the
   * session's phase (not a one-off "just started finalizing" flag), so
   * it resumes polling on its own if the component mounts with the
   * session already "finalizing" -- e.g. after a page reload while a
   * long finalize run is still in progress.
   */
  useEffect(() => {
    if (!isFinalizing(session)) return;

    let cancelled = false;

    const poll = () => {
      getQualitativeSession(conversationId, column)
        .then((res) => {
          if (cancelled) return;
          setSession(res.session);
          if (isFinalizeComplete(res.session)) {
            onFinalizedRef.current?.(buildFinalizedOutcome(column, res.session));
          } else if (isFinalizeFailed(res.session)) {
            setError(finalizeErrorMessage(res.session));
          }
        })
        .catch((err) => {
          if (!cancelled) setError(err.message || "Could not check the finalize status.");
        });
    };

    const intervalId = setInterval(poll, FINALIZE_POLL_INTERVAL_MS);

    return () => {
      cancelled = true;
      clearInterval(intervalId);
    };
  }, [session?.phase, conversationId, column]);

  useEffect(() => {
    if (!session) return;
    setCodeSelections(
      Object.fromEntries(
        (session.codes || []).map((c) => [
          c.id,
          { status: c.status || "pending", edited_name: c.edited_name || "" },
        ])
      )
    );
  }, [session]);

  const loadThemesFromSession = useCallback((s) => {
    const themes = (s.candidate_themes || []).map((t) => ({ ...t }));
    setActiveThemes(themes);
    setThemeSelections(
      Object.fromEntries(
        themes.map((t) => [
          t.id,
          {
            status: t.status || "pending",
            edited_name: t.edited_name || "",
            edited_description: t.edited_description || "",
          },
        ])
      )
    );
    const initialMembership = {};
    themes.forEach((t) => {
      (t.code_ids || []).forEach((cid) => {
        initialMembership[cid] = t.id;
      });
    });
    setMembership(initialMembership);
  }, []);

  const acceptedCodes = useMemo(
    () => (session?.codes || []).filter((c) => codeSelections[c.id]?.status === "accepted"),
    [session, codeSelections]
  );

  const { nodes: graphNodes, edges: graphEdges, themeX } = useMemo(
    () => computeLayout(acceptedCodes, activeThemes, membership),
    [acceptedCodes, activeThemes, membership]
  );

  const onNodeDragStop = useCallback(
    (_event, node) => {
      if (!node.id.startsWith("code:")) return;
      const codeId = node.id.slice("code:".length);
      let nearest = null;
      let nearestDistance = Infinity;
      themeX.forEach((x, themeId) => {
        const distance = Math.abs(x - node.position.x);
        if (distance < nearestDistance) {
          nearestDistance = distance;
          nearest = themeId;
        }
      });
      if (nearest) {
        setMembership((prev) => ({ ...prev, [codeId]: nearest }));
      }
    },
    [themeX]
  );

  if (loading) {
    return <p className="analysis-reasoning">Loading the qualitative review…</p>;
  }

  if (error && !session) {
    return (
      <div className="analysis-warning">
        <strong>Could not load this review</strong>
        <span>{error}</span>
      </div>
    );
  }

  if (!session) return null;

  function handleContinueToCoding() {
    setStep("code");
  }

  async function handleGroupIntoThemes() {
    setBusy(true);
    setError("");
    try {
      const codes = Object.entries(codeSelections).map(([id, sel]) => ({
        id,
        status: sel.status,
        edited_name: sel.edited_name || null,
      }));
      await submitCodeReview(conversationId, column, codes);
      const res = await groupCodesIntoThemes(conversationId, column);
      setSession(res.session);
      loadThemesFromSession(res.session);
      setStep("group");
    } catch (err) {
      setError(err.message || "Could not group codes into themes.");
    } finally {
      setBusy(false);
    }
  }

  function handleAcceptMerge(theme) {
    const targetId = theme.merge_with;
    if (!targetId) return;
    setMembership((prev) => {
      const next = { ...prev };
      Object.keys(next).forEach((codeId) => {
        if (next[codeId] === theme.id) next[codeId] = targetId;
      });
      return next;
    });
    setActiveThemes((prev) => prev.filter((t) => t.id !== theme.id));
  }

  function handleAcceptSplit(theme) {
    const baseName = themeLabel(theme);
    const partA = {
      id: `${theme.id}-a`,
      name: `${baseName} (part 1)`,
      description: theme.edited_description || theme.description,
      code_ids: [],
      status: "pending",
      edited_name: null,
      edited_description: null,
      verdict: "keep",
      verdict_notes: "",
      merge_with: null,
    };
    const partB = {
      id: `${theme.id}-b`,
      name: `${baseName} (part 2)`,
      description: theme.edited_description || theme.description,
      code_ids: [],
      status: "pending",
      edited_name: null,
      edited_description: null,
      verdict: "keep",
      verdict_notes: "",
      merge_with: null,
    };
    setActiveThemes((prev) => [...prev.filter((t) => t.id !== theme.id), partA, partB]);
    setThemeSelections((prev) => ({
      ...prev,
      [partA.id]: { status: "pending", edited_name: "", edited_description: "" },
      [partB.id]: { status: "pending", edited_name: "", edited_description: "" },
    }));
    setMembership((prev) => {
      const next = { ...prev };
      Object.keys(next).forEach((codeId) => {
        if (next[codeId] === theme.id) next[codeId] = partA.id;
      });
      return next;
    });
  }

  function handleDismissVerdict(theme) {
    setActiveThemes((prev) => prev.map((t) => (t.id === theme.id ? { ...t, verdict: "keep" } : t)));
  }

  async function handleContinueToThemeReview() {
    setBusy(true);
    setError("");
    try {
      const themePayload = activeThemes.map((theme) => ({
        id: theme.id,
        status: themeSelections[theme.id]?.status || "pending",
        edited_name: theme.name.includes("(part ") ? theme.name : themeSelections[theme.id]?.edited_name || null,
        edited_description: themeSelections[theme.id]?.edited_description || null,
        code_ids: acceptedCodes
          .filter((code) => (membership[code.id] || activeThemes[0]?.id) === theme.id)
          .map((code) => code.id),
      }));
      const res = await submitThemeReview(conversationId, column, themePayload);
      setSession(res.session);
      loadThemesFromSession(res.session);
      setStep("review");
    } catch (err) {
      setError(err.message || "Could not save the theme grouping.");
    } finally {
      setBusy(false);
    }
  }

  async function handleContinueToDefine() {
    setBusy(true);
    setError("");
    try {
      const themePayload = activeThemes.map((theme) => ({
        id: theme.id,
        status: themeSelections[theme.id]?.status || "pending",
        edited_name: themeSelections[theme.id]?.edited_name || null,
        edited_description: themeSelections[theme.id]?.edited_description || null,
      }));
      await submitThemeReview(conversationId, column, themePayload);
      const res = await defineQualitativeThemes(conversationId, column);
      setSession(res.session);
      setStep("define");
    } catch (err) {
      setError(err.message || "Could not define themes.");
    } finally {
      setBusy(false);
    }
  }

  async function handleFinalize() {
    setBusy(true);
    setError("");
    try {
      // Starts the background finalize task and returns almost
      // immediately with phase "finalizing" -- the polling effect above
      // picks it up from here via session.phase and reports completion
      // or failure once it lands.
      const res = await finalizeQualitativeThemes(conversationId, column);
      setSession(res.session);
      setStep(stepForPhase(res.session.phase));
    } catch (err) {
      setError(err.message || "Could not finalize themes.");
    } finally {
      setBusy(false);
    }
  }

  const acceptedThemeCount = Object.values(themeSelections).filter((s) => s.status === "accepted").length;
  const pendingVerdictThemes = activeThemes.filter((t) => t.verdict && t.verdict !== "keep");

  return (
    <div className="qualitative-review">
      <div className="qualitative-review-steps">
        {["familiarize", "code", "group", "review", "define"].map((s, i) => (
          <span key={s} className={`qualitative-review-step ${step === s ? "active" : ""}`}>
            {i + 1}. {{
              familiarize: "Familiarize",
              code: "Initial coding",
              group: "Search for themes",
              review: "Review themes",
              define: "Define & name",
            }[s]}
          </span>
        ))}
      </div>

      {error && (
        <div className="analysis-warning">
          <strong>Something went wrong</strong>
          <span>{error}</span>
        </div>
      )}

      {step === "familiarize" && (
        <div className="qualitative-familiarize">
          <p className="analysis-reasoning">{session.overview}</p>
          <div className="theme-excerpts">
            <small>Notable responses worth a closer look</small>
            {(session.notable_responses || []).map((n, i) => (
              <blockquote key={i}>
                <strong>{n.respondent_id}</strong> — {n.why_notable}
              </blockquote>
            ))}
          </div>
          <div className="analysis-action-bar">
            <div>
              <strong>{(session.codes || []).length} suggested codes ready for review</strong>
              <span>Adanse has read through every response and proposed an initial code for each.</span>
            </div>
            <button className="btn btn-primary" type="button" onClick={handleContinueToCoding}>
              Continue to coding →
            </button>
          </div>
        </div>
      )}

      {step === "code" && (
        <div className="dataset-variable-list">
          {(session.codes || []).map((code) => {
            const selection = codeSelections[code.id] || { status: "pending", edited_name: "" };
            return (
              <div className="dataset-variable-row grouping-suggestion" key={code.id}>
                <label className="dataset-grouping-checkbox">
                  <input
                    type="checkbox"
                    checked={selection.status === "accepted"}
                    onChange={() =>
                      setCodeSelections((prev) => ({
                        ...prev,
                        [code.id]: {
                          ...selection,
                          status: selection.status === "accepted" ? "declined" : "accepted",
                        },
                      }))
                    }
                    disabled={busy}
                  />
                  {TAG_LABEL(selection.status)}
                </label>

                <div className="dataset-variable-main">
                  {(code.extracts || []).map((extract, i) => (
                    <span className="dataset-grouping-variants" key={i}>
                      <strong>{extract.respondent_id}</strong>: “{extract.quote}”
                    </span>
                  ))}
                </div>

                <div className="dataset-grouping-canonical">
                  <label>Code name</label>
                  <input
                    type="text"
                    value={selection.edited_name || code.code_name}
                    onChange={(event) =>
                      setCodeSelections((prev) => ({
                        ...prev,
                        [code.id]: { ...selection, edited_name: event.target.value },
                      }))
                    }
                    disabled={busy}
                  />
                </div>
              </div>
            );
          })}

          <div className="analysis-action-bar">
            <div>
              <strong>{acceptedCodes.length} of {(session.codes || []).length} codes accepted</strong>
              <span>Accepted codes are grouped into candidate themes next.</span>
            </div>
            <button
              className="btn btn-primary"
              type="button"
              onClick={handleGroupIntoThemes}
              disabled={busy || !(session.codes || []).some((c) => codeSelections[c.id]?.status === "accepted")}
            >
              {busy ? "Grouping…" : "Group into themes →"}
            </button>
          </div>
        </div>
      )}

      {step === "group" && (
        <div className="qualitative-graph">
          <p className="analysis-reasoning">
            Drag a code onto a different theme to regroup it. AI-flagged themes below can be merged or split before
            you continue to review.
          </p>

          {pendingVerdictThemes.map((theme) => (
            <VerdictBanner
              key={theme.id}
              theme={theme}
              activeThemes={activeThemes}
              onAcceptMerge={handleAcceptMerge}
              onAcceptSplit={handleAcceptSplit}
              onDismiss={handleDismissVerdict}
              busy={busy}
            />
          ))}

          <div className="qualitative-flow-container">
            <ReactFlow
              nodes={graphNodes}
              edges={graphEdges}
              onNodeDragStop={onNodeDragStop}
              nodesConnectable={false}
              fitView
            >
              <Background gap={16} />
              <Controls showInteractive={false} />
            </ReactFlow>
          </div>
          <div className="analysis-action-bar">
            <div>
              <strong>{activeThemes.length} candidate themes</strong>
              <span>Confirm this grouping to move on to naming and reviewing each theme.</span>
            </div>
            <button className="btn btn-primary" type="button" onClick={handleContinueToThemeReview} disabled={busy}>
              {busy ? "Saving…" : "Continue to theme review →"}
            </button>
          </div>
        </div>
      )}

      {step === "review" && (
        <div className="dataset-variable-list">
          {activeThemes.map((theme) => {
            const selection = themeSelections[theme.id] || { status: "pending" };
            return (
              <article className="theme-card qualitative-theme-review-card" key={theme.id}>
                <label className="dataset-grouping-checkbox">
                  <input
                    type="checkbox"
                    checked={selection.status === "accepted"}
                    onChange={() =>
                      setThemeSelections((prev) => ({
                        ...prev,
                        [theme.id]: {
                          ...selection,
                          status: selection.status === "accepted" ? "declined" : "accepted",
                        },
                      }))
                    }
                    disabled={busy}
                  />
                  {TAG_LABEL(selection.status)}
                </label>

                <div className="dataset-grouping-canonical">
                  <label>Theme name</label>
                  <input
                    type="text"
                    value={selection.edited_name || theme.name}
                    onChange={(event) =>
                      setThemeSelections((prev) => ({
                        ...prev,
                        [theme.id]: { ...selection, edited_name: event.target.value },
                      }))
                    }
                    disabled={busy}
                  />
                </div>

                <div className="dataset-grouping-canonical">
                  <label>Description</label>
                  <textarea
                    rows={3}
                    value={selection.edited_description || theme.description}
                    onChange={(event) =>
                      setThemeSelections((prev) => ({
                        ...prev,
                        [theme.id]: { ...selection, edited_description: event.target.value },
                      }))
                    }
                    disabled={busy}
                  />
                </div>
              </article>
            );
          })}

          <div className="analysis-action-bar">
            <div>
              <strong>{acceptedThemeCount} of {activeThemes.length} themes accepted</strong>
              <span>Continuing defines the central concept and subthemes for each accepted theme.</span>
            </div>
            <button className="btn btn-primary" type="button" onClick={handleContinueToDefine} disabled={busy || acceptedThemeCount === 0}>
              {busy ? "Defining…" : "Continue to define & name →"}
            </button>
          </div>
        </div>
      )}

      {step === "define" && (
        <div className="qualitative-define">
          {(session.defined_themes || []).map((theme) => (
            <article className="theme-card" key={theme.id}>
              <div className="theme-header">
                <div>
                  <h5>{theme.name}</h5>
                  <p>{theme.central_organizing_concept}</p>
                </div>
                {theme.prevalence_estimate && <span>{theme.prevalence_estimate}</span>}
              </div>
              {(theme.subthemes || []).length > 0 && (
                <div className="theme-excerpts">
                  <small>Subthemes</small>
                  {theme.subthemes.map((s, i) => (
                    <blockquote key={i}>
                      <strong>{s.name}</strong> — {s.description}
                    </blockquote>
                  ))}
                </div>
              )}
            </article>
          ))}

          {isFinalizing(session) ? (
            <div className="analysis-action-bar">
              <div>
                <strong>{FINALIZE_HEADLINE}</strong>
                <span>{finalizeStepText(session)}</span>
              </div>
              <button className="btn btn-primary" type="button" disabled>
                Finalizing…
              </button>
            </div>
          ) : (
            <div className="analysis-action-bar">
              <div>
                <strong>{isFinalizeFailed(session) ? "Finalizing failed. You can try again." : "Ready to produce the report."}</strong>
                <span>Finalizing recounts these themes across every response and writes the Chapter 4 report.</span>
              </div>
              <button className="btn btn-primary" type="button" onClick={handleFinalize} disabled={busy}>
                {busy ? "Starting…" : isFinalizeFailed(session) ? "Retry finalize →" : "Finalize themes →"}
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
