import {useState} from "react";
import {parsePlannedSample, plannedSamplePayload, savedPlannedSample} from "../plannedSample.js";
import ChapterFill from "./ChapterFill.jsx";
function ListEditor({label,help,value,onChange,placeholder}){
 const [draft,setDraft]=useState("");
 const add=()=>{const v=draft.trim();if(v){onChange([...value,v]);setDraft("");}};
 return <div className="field-block"><label>{label}</label>{help&&<p className="field-help">{help}</p>}<div className="list-editor">{value.map((v,i)=><div className="list-chip" key={`${v}-${i}`}><span>{v}</span><button type="button" onClick={()=>onChange(value.filter((_,x)=>x!==i))}>×</button></div>)}<div className="list-add"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(e.preventDefault(),add())} placeholder={placeholder}/><button type="button" onClick={add}>Add</button></div></div></div>
}
export default function ThesisSetup({initial,onSave,loading}){
 const [title,setTitle]=useState(initial?.title||""); const [objectives,setObjectives]=useState(initial?.objectives||[]); const [questions,setQuestions]=useState(initial?.research_questions||[]); const [hypotheses,setHypotheses]=useState(initial?.hypotheses||[]); const [methodology,setMethodology]=useState(initial?.methodology||""); const [plannedSample,setPlannedSample]=useState(()=>{const size=savedPlannedSample(initial);return size?String(size):"";}); const plannedSampleError=parsePlannedSample(plannedSample).error;
 const applyChapterFill=c=>{if(c.title)setTitle(c.title);if(c.objectives)setObjectives(c.objectives);if(c.research_questions)setQuestions(c.research_questions);if(c.hypotheses)setHypotheses(c.hypotheses);if(c.plannedSample!==undefined)setPlannedSample(c.plannedSample);};
 const submit=e=>{e.preventDefault();if(!title.trim()||plannedSampleError)return;onSave({title:title.trim(),objectives,research_questions:questions,hypotheses,methodology,...plannedSamplePayload(plannedSample,initial)});};
 return <section className="setup-card"><div className="section-kicker">01 · RESEARCH CONTEXT</div><h1>Tell Adanse what you're researching.</h1><p className="section-lead">Give Adanse the context behind your thesis. You don't need to know which statistical test to use — we'll map your research to the data.</p><ChapterFill current={{title,objectives,research_questions:questions,hypotheses}} onApply={applyChapterFill} disabled={loading}/><form onSubmit={submit}><div className="field-block"><label>Thesis title or topic</label><input className="text-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. The influence of artificial intelligence tools on academic performance among undergraduate students" required/></div><ListEditor label="Research objectives" help="Add the objectives exactly as they appear in your proposal." value={objectives} onChange={setObjectives} placeholder="e.g. To examine the extent of AI tool usage..."/><ListEditor label="Research questions" help="Optional, but useful when your questions differ from your objectives." value={questions} onChange={setQuestions} placeholder="e.g. What is the extent of AI tool usage?"/><ListEditor label="Hypotheses" help="Optional. Adanse will preserve your wording when testing them." value={hypotheses} onChange={setHypotheses} placeholder="e.g. H1: AI usage is significantly associated with GPA."/><div className="field-block"><label>Methodology / research design <span>optional</span></label><textarea className="text-input textarea" value={methodology} onChange={e=>setMethodology(e.target.value)} placeholder="e.g. Cross-sectional survey of undergraduate students..." rows={4}/></div><div className="field-block"><label htmlFor="planned-sample-size">Planned sample size <span>optional</span></label><p className="field-help">How many respondents your study planned to reach, as stated in your Chapter 3. Adanse uses it to report your response rate in Chapter 4.</p><input id="planned-sample-size" className="text-input sample-size-input" inputMode="numeric" value={plannedSample} onChange={e=>setPlannedSample(e.target.value)} placeholder="e.g. 200" aria-invalid={Boolean(plannedSampleError)} aria-describedby={plannedSampleError?"planned-sample-size-error":undefined}/>{plannedSampleError&&<p className="field-error" id="planned-sample-size-error">{plannedSampleError}</p>}</div><button className="btn btn-primary btn-large" disabled={loading||!title.trim()||Boolean(plannedSampleError)}>{loading?"Saving…":"Save research context →"}</button></form></section>
}
